/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.*;
import interfaz_proyectofinal.Interfaz_Proyectofinal;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author asha2
 */
public class nuevo2_empleado extends javax.swing.JFrame {

    /**
     * Creates new form nuevo2_empleado
     */
    public int posicion = 0;
    public ver2_empleados ventana = new ver2_empleados();
    //Se crea una ventana de ver2 (vendedor) para recuperar la clave en caso de querer modificar un empleado

    public nuevo2_empleado() {
        initComponents();
        setLocationRelativeTo(null);//Para que al ejecutarse se presente en medio de la pantalla
        inicializarDatos();
        //Método para llenar datos en caso que se haya decidido modificar algún empleado   
    }
    
    public void inicializarDatos(){  
        try{//Recorremos la lista de empleados
            while(posicion<Interfaz_Proyectofinal.listaEmpleados.size()){
                //Haciendo uso del polimorfismo, recorremos únicamente los de tipo vendedor
                //Se usa la clave para identificar al empleado a modificar
                if(Interfaz_Proyectofinal.listaEmpleados.get(posicion)instanceof Vendedor){
                    //Sólo en el caso de que coincidan la clave con la del empleado buscado, los campos de texto
                    //se llenarán con sus respectivos datos, listos para ser modificados
                    if(ventana.Clave_modificacion.equals(Interfaz_Proyectofinal.listaEmpleados.get(posicion).getClave()) == true){
                        //Se recuperan los datos
                        this.txtNombre.setText(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getNombre());
                        this.txtApellido.setText(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getApellido());
                        this.txtDias.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getDias()));
                        this.txtClave.setText(ventana.Clave_modificacion);
                        this.txtSueldoBase.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getSueldoBase()));
                        this.txtPrestamo.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getPrestamo()));
                        this.txtTasaDescuento.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getTasaDescInfona()));                
                        this.txtTarifaComision.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getTarifaComision()));
                        this.txtVentas.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getVentasDelVendedor()));
                        this.txtCochesVendidos.setText(String.valueOf(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(posicion)).getAutosVendidos()));
                        Interfaz_Proyectofinal.listaEmpleados.remove(posicion); 
                        //Se quitará el empleado de la lista para poder ser modificado
                        break;//Ya ha sido encontrado el empleado, por lo que ya no es necesario seguir con la lista
                }            
            }
            posicion++;
            //Contador necesario que se actualizará hasta obtener la posición del empleado a modificar
        }
        ventana.Clave_modificacion = "";
        //Se vacía la cadena de la clave de modificación en el caso que se quiera modificar algún otro empleado
    }catch(ClassCastException e1){
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error.");
    }
    }
    
    //Método necesario para validar que el empleado a guardar no tenga una clave repetida de algún otro empleado vendedor
    private boolean Clave_repetida(String clave){
        boolean repetido = false;
        
        for(int i = 0; i<Interfaz_Proyectofinal.listaEmpleados.size();i++){
            if(Interfaz_Proyectofinal.listaEmpleados.get(i)instanceof Vendedor){
                //Pueden tener la misma clave si son de distintas clases de empleado
                if(((Vendedor)Interfaz_Proyectofinal.listaEmpleados.get(i)).getClave().equals(clave)){
                   repetido = true;
                }
            }   
        }        
        return repetido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        txtSueldoBase = new javax.swing.JTextField();
        txtPrestamo = new javax.swing.JTextField();
        txtTarifaComision = new javax.swing.JTextField();
        txtVentas = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCochesVendidos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTasaDescuento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Seleccione el tipo de empleado (1).png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (1).png"))); // NOI18N
        jLabel3.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (3).png"))); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (4).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (5).png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (8).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (9).png"))); // NOI18N
        jLabel8.setText("jLabel8");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        txtDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiasKeyPressed(evt);
            }
        });

        txtSueldoBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSueldoBaseKeyPressed(evt);
            }
        });

        txtPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrestamoKeyPressed(evt);
            }
        });

        txtTarifaComision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTarifaComisionKeyPressed(evt);
            }
        });

        txtVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVentasKeyPressed(evt);
            }
        });

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Copia de nombre (2).png"))); // NOI18N
        btGuardar.setText("jButton1");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (10).png"))); // NOI18N
        jLabel9.setText("jLabel9");

        txtCochesVendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCochesVendidosKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (18).png"))); // NOI18N

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre (22).png"))); // NOI18N

        txtTasaDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTasaDescuentoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrestamo)
                            .addComponent(txtTasaDescuento)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtSueldoBase, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDias, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtTarifaComision, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtCochesVendidos)
                            .addComponent(txtClave))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTarifaComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCochesVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTasaDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Método para limpiar los campos de texto 
    private void LimpiarCampos(){
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtClave.setText("");
        this.txtDias.setText("");
        this.txtCochesVendidos.setText("");
        this.txtPrestamo.setText("");
        this.txtSueldoBase.setText("");
        this.txtTarifaComision.setText("");
        this.txtVentas.setText("");
        this.txtTasaDescuento.setText("");
    }
    
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        try{
            //Se guardan en variables lo registrado en las cajas de texto
            String clave = this.txtClave.getText();
            String nombre = this.txtNombre.getText();
            String apellido = this.txtApellido.getText();
            int dias = Integer.parseInt(this.txtDias.getText());
            double sueldoBase = Double.parseDouble(this.txtSueldoBase.getText());
            double prestamo = Double.parseDouble(this.txtPrestamo.getText());
            double tasaDescInfona = Double.parseDouble(this.txtTasaDescuento.getText());
            double tarifaComision = Double.parseDouble(this.txtTarifaComision.getText());
            double ventas = Double.parseDouble(this.txtVentas.getText());
            int autosVendidos = Integer.parseInt(this.txtCochesVendidos.getText());
            
            //Se lanzará un error personalizado en el caso de que se pongan números negativos
            if(dias <= 0 || sueldoBase<= 0 || prestamo<=0 || tasaDescInfona<=0 || tarifaComision<=0 || ventas<0 || autosVendidos<0){
                throw new RuntimeException();
            }

            //En caso que no se haya registrado un empleado con la misma clave, se guardará el empleado
            if(Clave_repetida(clave) == false){
                JOptionPane.showMessageDialog(this, "Vendedor "+nombre+" guardado con éxito.","Nuevo vendedor registrado.",JOptionPane.INFORMATION_MESSAGE);
                this.LimpiarCampos();//Se limpian los campos una vez guardado el empleado

                //Se hace uso del polimorfismo, creando un tipo empleado con parámetros de vendedor
                Empleado empleado = new Vendedor(clave,nombre,apellido,dias,sueldoBase,prestamo,tasaDescInfona,tarifaComision,ventas,autosVendidos);
                Interfaz_Proyectofinal.listaEmpleados.add(empleado);    
                //Se guarda en el arraylist de empleados
                int opcion = JOptionPane.showConfirmDialog(this, "¿Desea registrar otro empleado?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);        
                //En el caso de que se haya seleccionado "No", se cerrará dicha ventana y se abrirá la de empleados
                if(opcion == JOptionPane.NO_OPTION){
                    ventana_empleados Ventana_empleados = new ventana_empleados();
                    this.dispose();
                    Ventana_empleados.setVisible(true);
                }//Cierra la ventana
                
            }else{
                    //Significa que ya se ha registrado un empleado del mismo tipo con la misma clave
                    JOptionPane.showMessageDialog(this, "Ya existe un empleado con la clave " + clave,"Error al intentar registrar empleado.",JOptionPane.WARNING_MESSAGE);
                }
            
        }
        catch(NumberFormatException e1){
            JOptionPane.showMessageDialog(this, "Es necesario llenar los campos correctamente.","Advertencia de error.",JOptionPane.WARNING_MESSAGE);
        }
        catch (RuntimeException e2){
            JOptionPane.showMessageDialog(this, "Es necesario llenar los campos correctamente \n(los valores no pueden ser menores o iguales a cero).","Advertencia de error.",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        //Dependiendo de la tecla presionada, se dirigirá y seleccionará al siguiente campo de texto
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtApellido.requestFocus(); break;
            case KeyEvent.VK_RIGHT: 
                this.txtTarifaComision.requestFocus(); break;
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtDias.requestFocus(); break;
            case KeyEvent.VK_RIGHT: 
                this.txtVentas.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtNombre.requestFocus();break;
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtDiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtSueldoBase.requestFocus(); break;
            case KeyEvent.VK_RIGHT: 
                this.txtCochesVendidos.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtApellido.requestFocus();break;
        }
    }//GEN-LAST:event_txtDiasKeyPressed

    private void txtSueldoBaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBaseKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtPrestamo.requestFocus(); break;
            case KeyEvent.VK_RIGHT: 
                this.txtClave.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtDias.requestFocus();break;
        }
    }//GEN-LAST:event_txtSueldoBaseKeyPressed

    private void txtPrestamoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrestamoKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtTasaDescuento.requestFocus(); break;
            case KeyEvent.VK_RIGHT: 
                this.txtClave.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtSueldoBase.requestFocus();break;
        }
    }//GEN-LAST:event_txtPrestamoKeyPressed

    private void txtTasaDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTasaDescuentoKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_RIGHT: 
                this.txtClave.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtPrestamo.requestFocus();break;
        }
    }//GEN-LAST:event_txtTasaDescuentoKeyPressed

    private void txtTarifaComisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaComisionKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtVentas.requestFocus(); break;
            case KeyEvent.VK_LEFT: 
                this.txtNombre.requestFocus(); break;
        }
    }//GEN-LAST:event_txtTarifaComisionKeyPressed

    private void txtVentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVentasKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtCochesVendidos.requestFocus(); break;
            case KeyEvent.VK_LEFT: 
                this.txtApellido.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtTarifaComision.requestFocus();break;
        }
    }//GEN-LAST:event_txtVentasKeyPressed

    private void txtCochesVendidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCochesVendidosKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_DOWN: 
                this.txtClave.requestFocus(); break;
            case KeyEvent.VK_LEFT: 
                this.txtDias.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtVentas.requestFocus();break;
        }
    }//GEN-LAST:event_txtCochesVendidosKeyPressed

    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_LEFT: 
                this.txtSueldoBase.requestFocus(); break;
            case KeyEvent.VK_UP:
                this.txtCochesVendidos.requestFocus();break;
        }
    }//GEN-LAST:event_txtClaveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo2_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo2_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo2_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo2_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevo2_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCochesVendidos;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrestamo;
    private javax.swing.JTextField txtSueldoBase;
    private javax.swing.JTextField txtTarifaComision;
    private javax.swing.JTextField txtTasaDescuento;
    private javax.swing.JTextField txtVentas;
    // End of variables declaration//GEN-END:variables
}
